### ISSUE TITLE
Presets LV2

### ISSUE THREAD

**Issue by trebmuh** [sonejostudios/Panoramix#2]
@sonejostudios : salut Vinz (ici olinuxx de linuxmao).

Je suis en train d'empaqueter Panoramix pour le mettre dans LibraZiK-2.

Je me demande où doit être placé le dossier de presets LV2 pour qu'il soit correctement pris en compte ? Pour l'instant, j'ai ça :
```
$ ls /usr/lib/lv2/Panoramix.lv2/
manifest.ttl  Panoramix.so  Panoramix.ttl
```
si je place les fichiers de préréglages ici, alors lv2ls ne voit plus Panoramix.

Bref, avant de faire de multiples tests, je venais voir ici si tu avais l'info !

**Comment by sonejostudios** [comment]
Salut Olinuxx!

chez moi (linuxmint 19 = ubuntu 18.04), les presets sont dans le même dossier que tous les .lv2.

chez moi ils sont dans home

/home/vince/.lv2/Panoramix.lv2
/home/vince/.lv2/Panoramix.presets.lv2

hmm la dernière fois tout marchait bien, par contre je viens de voir que les presets ne sont plus visibles, chez moi non plus! C'est a voir comment regler le problème....

Je te propose donc d'intégrer Panoramix sans le presets (ils n'étaient pas si important non plus)!

a+ et merci

**Comment by trebmuh** [comment]
Merci pour la réponse. Du coup, en les mettant dans 
`/usr/lib/.lv2/Panoramix.presets.lv2/` (installation côté système), ça fonctionne et ils sont fonctionnels avec jalv.select .

Je ferme du coup, encore merci !
