### ISSUE TITLE
Plugin URI assigned by faust2lv2 does not match the one used in presets

### ISSUE THREAD

**Issue by SpotlightKid** [sonejostudios/Panoramix#3]
When I generate an LV2 plugin from the FAUST source with `faust2lv2 Panoramix.dsp` the plugin URI in the generated `manifest.ttl` is `https://faustlv2.bitbucket.io/Panoramix`. But the `manifest.ttl` in the `Panoramix.presets.lv2` bundle uses `http://faustlv2.bitbucket.org/Panoramix` for the `lv2:appliesTo` property of the presets.

The presets are therefore not found by LV2 hosts.

**Comment by sonejostudios** [comment]
Hi @SpotlightKid ,

thanks for the issue! I think I fixed it, could you try now?
All the best

**Comment by SpotlightKid** [comment]
Yes, all good now. Thanks!
